name: pizza
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-27.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.0
  zoom_tap_animation: ^1.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.4.0
  flutter_bloc: ^8.1.3
  dio: ^4.0.6
  equatable: ^2.0.5
  sqflite: ^2.3.0
  permission_handler: ^11.0.0
  awesome_dialog: ^3.1.0
  light: ^3.0.1
  dot_navigation_bar: ^1.0.2
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          style: italic

