name: pizza
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-27.0.dev <4.0.0'
#  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.8
  shared_preferences: ^2.2.2
  zoom_tap_animation: ^1.1.0
  cached_network_image: ^3.3.0
  lottie: ^2.7.0
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  dot_navigation_bar: ^1.0.2
  mask_text_input_formatter: ^2.5.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  path_provider: ^2.1.1

  badges: ^3.1.2
  google_sign_in: ^6.1.5
#  cloud_firestore: ^4.12.1
  cloud_firestore: ^4.12.1
  firebase_core: ^2.20.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          style: italic

